version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    commit-message:
      prefix: "go-deps"
    assignees:
    - "Harvester57"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "actions"
    assignees:
    - "Harvester57"
    schedule:
      interval: daily
